package alexandrelima.ladrilho.gui;

import alexandrelima.ladrilho.dominio.*;
import alexandrelima.ladrilho.gui.JogoDoLadrilho;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 *
 * Created on 11 de Agosto de 2004, 15:48
 */

/*
  Autor: Alexandre Gomes de Lima - alexlouco@zipmail.com.br
  Este c�digo � propriedade intelectual do autor. � permitida a livre utiliza��o para fins 
  did�ticos e educacionais sem fins lucrativos. Para mais informa��es, consulte o autor.
  */
public class JogoDesktop extends javax.swing.JFrame {
    
    public JogoDesktop() throws Exception{
        initComponents();
        
        PnlJogo jogo = new PnlJogo();
        //inserindo o jogo
        this.getContentPane().add( jogo, java.awt.BorderLayout.CENTER );
        this.setResizable( true );
        pack();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            new JogoDesktop().setVisible(true);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
}
